### ISSUE TITLE
Relation to Dengue work

### ISSUE THREAD

**Issue by madkopp** [caio-davi/covid-br#2]
Caio,

I read your paper about using ML to find genetic markers that correlate to the severity of Dengue (Severe Dengue Prognosis Using Human Genome Data and Machine Learning).  I'm interested if your team has considered using the same techniques for the COVID-19 disease.  It seems like the approach could be used to find who needs to be kept away from the virus, which healthcare workers need prophylactic treatments, which patients need early intervention by experimental treatments, etc.

Thanks,
Adam

**Comment by caio-davi** [comment]
Hi Adam,

I hope you are healthy and doing well. 
Thank you for your interest and insights. Yes, we intend to use that approach to find good classifiers to COVID-19. Currently, our group is looking for partnerships with clinical and genetic labs in order to get the necessary data.  

Cordially,
Caio Davi

PS.: I'll close this issue since it is not directly related to this project, ok?

**Comment by madkopp** [comment]
Hey Caio,

That's awesome, man.  It's cool to hear that this sort of work is going on - I hope you guys get what you need.

Purely out of curiosity, is this the sort of thing where agencies like the CDC or NIH would get involved?  Especially in terms of getting you that data.

Thanks for taking the time to respond.

-Adam
